baseurl = "https://southwestkoala.co.uk"
title = "Southwest Koala"
theme = "coder"
languagecode = "en-gb"
defaultcontentlanguage = "en-gb"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "southwestkoala"

[params]
    author = "Matthew Gibbons"
    info = "Quality Improvement Facilitator"
    description = "Matthew Gibbons, Quality Improvement Facilitator, Southwest Koala"
    keywords = "quality,improvement,facilitator"
    avatarurl = "images/avatar.jpg"

    footercontent = "koalas are cooler than kangeroos"

    hideCredits = false
    hideCopyright = false

    rtl = false

    custom_css = []

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/accuser/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://linkedin.com/in/matthewgibbons/"