baseurl = "https://southwestkoala.co.uk"
title = "Southwest Koala"
theme = "coder"
languagecode = "en-gb"
defaultcontentlanguage = "en-gb"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "southwestkoala"
googleAnalytics = "UA-35915992-1"

[params]
    author = "Matthew Gibbons"
    info = "Quality Improvement Coaching, Training, and Facilitation"
    description = "Matthew Gibbons, Quality Improvement Coach, Trainer, and Facilitator, Southwest Koala"
    keywords = "quality,improvement,coach,trainer,facilitator"
    avatarurl = "images/avatar.jpg"

    footercontent = "koalas are cooler than kangaroos"

    rtl = false

    custom_css = []

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/accuser/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/matthewgibbons/"
